#!/bin/bash

if [[ $# != 3 ]]; then
   echo "Usage: diff_conf SRV_NAME FROM_VER TO_VER"
   exit 1
fi

srv_name=$1
from_ver=$2
to_ver=$3

echo "sys.config"
diff ${srv_name}*-${to_ver}/releases/1/sys.config ${srv_name}*-${from_ver}/releases/1/sys.config

echo "vm.args"
diff ${srv_name}*-${to_ver}/releases/1/vm.args ${srv_name}*-${from_ver}/releases/1/vm.args
