#!/bin/bash

SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})
SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

if [[ "$(id -un)" == "root" ]]; then
    echo "Must not be root"
    exit 1
fi

source $SCRIPT_DIR/../conf/setup.conf

echo -e "\nStarting MongoDB db..."
NOFILE=$(ulimit -n)
NPROC=$(ulimit -u)
ulimit -n 64000 -u 32000
mongod --port 27017 --dbpath $DB_DIR/data/ --logpath $LOG_DIR/mongodb/mongodb.log --logappend --fork
ulimit -n $NOFILE -u $NPROC
ps x | grep [m]ongod.*27017 &> /dev/null
if [[ $? != 0 ]]; then
    echo "FAILED"
else
    echo "SUCCESS"
fi

echo -e "\nStarting RabbitMQ..."
rabbitmq-server -detached
sleep 30
rabbitmqctl status
if [ $? != 0 ]; then
    echo "FAILED"
else
    echo "SUCCESS"
fi

echo -e "\nStarting SMPPSim..."
pushd /opt/SMPPSim &> /dev/null
./startsmppsim.sh &> /dev/null &
popd >/dev/null &> /dev/null
echo "SUCCESS"
