#!/bin/bash

SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})
SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

if [[ "$(id -un)" == "root" ]]; then
    echo "Must not be root"
    exit 1
fi

source $SCRIPT_DIR/../conf/setup.conf

echo -e "\nStarting Funnel..."
/opt/funnel/bin/funnel start
sleep 10
F=`/opt/funnel/bin/funnel ping`
if [[ $F != 'pong' ]]; then
    echo $F
    echo "FAILED"
else
    echo "SUCCESS"
fi

echo -e "\nStarting SOAP Srv..."
/opt/soap_srv/bin/soap_srv start
sleep 10
S=`/opt/soap_srv/bin/soap_srv ping`
if [[ $S != 'pong' ]]; then
    echo $S
    echo "FAILED"
else
    echo "SUCCESS"
fi

echo -e "\nStarting OneAPI Srv..."
/opt/oneapi_srv/bin/oneapi_srv start
sleep 10
O=`/opt/oneapi_srv/bin/oneapi_srv ping`
if [[ $O != 'pong' ]]; then
    echo $O
    echo "FAILED"
else
    echo "SUCCESS"
fi

if [[ -x /opt/mm_srv/bin/mm_srv ]]; then
    echo -e "\nStarting MM Srv..."
    /opt/mm_srv/bin/mm_srv start
    sleep 10
    M=`/opt/mm_srv/bin/mm_srv ping`
    if [[ $M != 'pong' ]]; then
        echo $M
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi

echo -e "\nStarting Kelly..."
/opt/kelly/bin/kelly start
sleep 10
K=`/opt/kelly/bin/kelly ping`
if [[ $K != 'pong' ]]; then
    echo $K
    echo "FAILED"
else
    echo "SUCCESS"
fi

echo -e "\nStarting Just..."
/opt/just/bin/just start
sleep 20
J=`/opt/just/bin/just ping`
if [[ $J != 'pong' ]]; then
    echo $J
    echo "FAILED"
else
    echo "SUCCESS"
fi
