#!/bin/bash

echo
date
echo

if [[ "$(id -un)" == "root" ]]; then
    echo "Must not be root"
    exit 1
fi

ulimit -n 64000 -u 32000
mongod --replSet alley --dbpath /mnt/db/data --logpath /var/log/mongodb/mongodb.log --fork
