#!/bin/bash

SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})
SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

if [[ "$(id -un)" == "root" ]]; then
    echo "Must not be root"
    exit 1
fi

/opt/just/bin/just stop
/opt/kelly/bin/kelly stop
/opt/mm_srv/bin/mm_srv stop
/opt/oneapi_srv/bin/oneapi_srv stop
/opt/soap_srv/bin/soap_srv stop
/opt/funnel/bin/funnel stop
