#!/bin/bash

SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})
SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

if [[ "$(id -un)" == "root" ]]; then
    echo "Must not be root"
    exit 1
fi

killall mongod
rabbitmqctl stop
kill `ps x | grep [s]mppsim | awk '{ print $1 }'`
/opt/smppsink/bin/smppsink stop
