#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_SOAP == true ]]; then
        $SCRIPT_DIR/phase-build-soap $* || exit $?
    fi

    DIR_NAME=soap-srv-${SOAP_VER}
    TAR_NAME=soap-srv_${SOAP_VER}_${DISTRO}_$(uname -m).tar.gz

    tar -C /opt -xzf $SCRIPT_DIR/../distr/${TAR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack soap_srv
        exit 1
    fi

    mkdir -p $DATA_DIR/soap_srv/data $LOG_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir soap_srv
        exit 1
    fi

    pushd /opt/${DIR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to change dir to /opt/${DIR_NAME}
        exit 1
    fi

    cp -r -u data/* $DATA_DIR/soap_srv/data
    if [[ $? -ne 0 ]]; then
        echo Failed to copy soap_srv data
        exit 1
    fi

    cp -r -u log/* $LOG_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to copy soap_srv log
        exit 1
    fi

    rm -rf data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm soap_srv data
        exit 1
    fi

    rm -rf log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm soap_srv log
        exit 1
    fi

    ln -s $DATA_DIR/soap_srv/data data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv data
        exit 1
    fi

    ln -s $LOG_DIR/soap_srv log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv log
        exit 1
    fi

    popd

    # remove old link
    previous=`readlink /opt/soap_srv`
    if [[ "$previous" != "" ]]; then
        rm /opt/soap_srv
    fi

    # setup link
    ln -s /opt/${DIR_NAME} /opt/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv
        exit 1
    fi

    # change app configuration warning
    if [[ "$previous" != "" ]]; then
        echo diff $previous/releases/1/sys.config /opt/soap_srv/releases/1/sys.config
        diff $previous/releases/1/sys.config /opt/soap_srv/releases/1/sys.config
        if [[ $? -ne 0 ]]; then
            cat << EOF
WARNING!
Don't forget to change application configuration.
EOF
        fi
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/${DIR_NAME} /opt/soap_srv $DATA_DIR/soap_srv $LOG_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to chown soap_srv
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
