#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_SOAP == true ]]; then
        source $SCRIPT_DIR/phase-build-soap
    fi

    tar -C /opt -xzf $SCRIPT_DIR/../distr/soap_srv-$SOAP_VER-$DISTRO-x86_64.tar.gz
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack soap_srv
        exit 1
    fi

    # TODO: on upgrade the link may already exist
    ln -s /opt/soap_srv-$SOAP_VER-$DISTRO-x86_64 /opt/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv
        exit 1
    fi

    # create soap_srv dirs
    mkdir -p $DATA_DIR/soap_srv $LOG_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir soap_srv
        exit 1
    fi

    cp -r /opt/soap_srv/data $DATA_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to copy soap_srv data
        exit 1
    fi

    cp -r /opt/soap_srv/log/* $LOG_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to copy soap_srv log
        exit 1
    fi

    rm -rf /opt/soap_srv/data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm soap_srv data
        exit 1
    fi

    rm -rf /opt/soap_srv/log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm soap_srv log
        exit 1
    fi

    ln -s $DATA_DIR/soap_srv/data /opt/soap_srv/data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv data
        exit 1
    fi

    ln -s $LOG_DIR/soap_srv /opt/soap_srv/log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv log
        exit 1
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/soap_srv-$SOAP_VER-$DISTRO-x86_64 /opt/soap_srv $DATA_DIR/soap_srv $LOG_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to chown soap_srv
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
