#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_MM == true ]]; then
        source $SCRIPT_DIR/phase-build-mm
    fi

    tar -C /opt -xzf $SCRIPT_DIR/../distr/mm_srv-$MM_VER-$DISTRO-x86_64.tar.gz
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack mm_srv
        exit 1
    fi

    # TODO: on upgrade the link may already exist
    ln -s /opt/mm_srv-$MM_VER-$DISTRO-x86_64 /opt/mm_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to ln mm_srv
        exit 1
    fi

    # create mm_srv dirs
    mkdir -p $DATA_DIR/mm_srv $LOG_DIR/mm_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir mm_srv
        exit 1
    fi

    cp -r /opt/mm_srv/data $DATA_DIR/mm_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to copy mm_srv data
        exit 1
    fi

    cp -r /opt/mm_srv/log/* $LOG_DIR/mm_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to copy mm_srv log
        exit 1
    fi

    rm -rf /opt/mm_srv/data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm mm_srv data
        exit 1
    fi

    rm -rf /opt/mm_srv/log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm mm_srv log
        exit 1
    fi

    ln -s $DATA_DIR/mm_srv/data /opt/mm_srv/data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln mm_srv data
        exit 1
    fi

    ln -s $LOG_DIR/mm_srv /opt/mm_srv/log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln mm_srv log
        exit 1
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/mm_srv-$MM_VER-$DISTRO-x86_64 /opt/mm_srv $DATA_DIR/mm_srv $LOG_DIR/mm_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to chown mm_srv
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
