#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    groupadd sudo

    # note, the password must be encrypted
    useradd -m -p $(openssl passwd -1 $ALLEY_PWD) -U -G sudo $ALLEY_USER -s /bin/bash
    case "$?" in
	"0") ;; # ok
	"9") ;; # already exists
	  *) 
            echo Failed to create $ALLEY_USER user
            exit 1
    esac

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
