#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

source $SCRIPT_DIR/phase-check-args

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    apt-get update -y
    if [[ $? -ne 0 ]]; then
        echo Failed to update
        exit 1
    fi

    apt-get install -y \
        build-essential \
        libssl-dev \
        libncurses5-dev \
        default-jdk \
        fop \
        xsltproc \
        git-core \
        screen \
        uuid-dev \
        libtokyocabinet-dev \
        snmp \
        htop \
        sysstat \
        iotop \
        wget \
        curl \
        tar \
        emacs

    if [[ $? -ne 0 ]]; then
        echo Failed to install deps
        exit 1
    fi

    # setup kerl (https://github.com/yrashk/kerl)
    cat > ~/.kerlrc <<EOF
export $ERLANG_ENV
KERL_CONFIGURE_OPTIONS="--without-wx --without-javac --without-odbc"
KERL_DEFAULT_INSTALL_DIR=/opt
KERL_INSTALL_MANPAGES=1
KERL_INSTALL_HTMLDOCS=1
EOF
    pushd /opt/bin
    curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
    chmod a+x kerl
    popd

    pushd /etc/bash_completion.d
    if [[ $? -eq 0 ]]; then
        ## perform only if there's /etc/bash_completion.d
        curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/bash_completion/kerl
        popd
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
