#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    pushd /opt/rabbitmq/sbin

    ./rabbitmq-plugins enable rabbitmq_management

    ./rabbitmq-server -detached
    sleep 10

    curl -O http://localhost:15672/cli/rabbitmqadmin 2> /dev/null
    if [[ $? -ne 0 ]]; then
        echo Failed to download rabbitmqadmin
        popd
        exit 1
    fi

    ./rabbitmqctl stop

    chmod +x ./rabbitmqadmin

    popd

    # we were under root, change permissions back.
    chown $ALLEY_USER:$ALLEY_USER -R /opt/rabbitmq_server-$RABBITMQ_VER /opt/rabbitmq $VAR_DIR/rabbitmq
    if [[ $? -ne 0 ]]; then
        echo Failed to chown for rabbitmq
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
