#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    SNMP_DIR=/etc/skel/.snmp
    mkdir -p $SNMP_DIR
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir $SNMP_DIR
        exit 1
    fi

    echo "mibdirs +/opt/funnel/mibs:/opt/just/mibs" >> $SNMP_DIR/snmp.conf
    echo "mibs +FUNNEL-MIB:JUST-MIB"                >> $SNMP_DIR/snmp.conf

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
