#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

source $SCRIPT_DIR/phase-check-args

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    rm -rf ${TMP_DIR?}/funnel_mini

    git clone https://github.com/PowerMeMobile/funnel_mini.git ${TMP_DIR?}/funnel_mini
    if [[ $? -ne 0 ]]; then
        echo Failed to clone funnel
        exit 1
    fi

    pushd ${TMP_DIR?}/funnel_mini

    git checkout $FUNNEL_VER
    if [[ $? -ne 0 ]]; then
        echo Failed to checkout funnel $FUNNEL_VER
        popd
        exit 1
    fi

    make
    if [[ $? -ne 0 ]]; then
        echo Failed to build funnel
        popd
        exit 1
    fi

    DIR_NAME=funnel_mini-${FUNNEL_VER}
    TAR_NAME=${DIR_NAME}-${DISTRO}.$(uname -m).tar.gz

    mv rel/funnel_mini ${DIR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to rename funnel release
        popd
        exit 1
    fi

    tar -czf ${TAR_NAME} ${DIR_NAME}/
    if [[ $? -ne 0 ]]; then
        echo Failed to pack funnel
        popd
        exit 1
    fi

    popd

    mv ${TMP_DIR?}/funnel_mini/${TAR_NAME} $SCRIPT_DIR/../distr/
    if [[ $? -ne 0 ]]; then
        echo Failed to move funnel to distr
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
