#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_SOAP == true ]]; then
        git clone https://github.com/PowerMeMobile/soap_srv.git $TMP_DIR/soap_srv
        if [[ $? -ne 0 ]]; then
            echo Failed to clone soap_srv
            exit 1
        fi

        pushd $TMP_DIR/soap_srv

        git checkout $SOAP_SRV_VER
        if [[ $? -ne 0 ]]; then
            echo Failed to checkout soap_srv $SOAP_VER
            popd
            exit 1
        fi

        make
        if [[ $? -ne 0 ]]; then
            echo Failed to build soap_srv
            popd
            exit 1
        fi

        mv rel/soap_srv soap_srv-$SOAP_VER-$DISTRO-x86_64
        if [[ $? -ne 0 ]]; then
            echo Failed to rename soap_srv release
            popd
            exit 1
        fi

        tar -czf soap_srv-$SOAP_VER-$DISTRO-x86_64.tar.gz soap_srv-$SOAP_VER-$DISTRO-x86_64/
        if [[ $? -ne 0 ]]; then
            echo Failed to pack soap_srv
            popd
            exit 1
        fi

        popd

        mv $TMP_DIR/soap_srv/soap_srv-$SOAP_VER-$DISTRO-x86_64.tar.gz $SCRIPT_DIR/../distr/
        if [[ $? -ne 0 ]]; then
            echo Failed to move soap_srv to distr
            popd
            exit 1
        fi

    fi

    tar -C /opt -xzf $SCRIPT_DIR/../distr/soap_srv-$SOAP_VER-$DISTRO-x86_64.tar.gz
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack soap_srv
        exit 1
    fi

    # TODO: on upgrade the link may already exist
    ln -s /opt/soap_srv-$SOAP_VER-$DISTRO-x86_64 /opt/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv
        exit 1
    fi

    # create Soap_Srv dirs
    mkdir -p $VAR_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir soap_srv
        exit 1
    fi

    cp -r /opt/soap_srv/data $VAR_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to copy soap_srv data
        exit 1
    fi

    cp -r /opt/soap_srv/log $VAR_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to copy soap_srv log
        exit 1
    fi

    rm -rf /opt/soap_srv/data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm soap_srv data
        exit 1
    fi

    rm -rf /opt/soap_srv/log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm soap_srv log
        exit 1
    fi

    ln -s $VAR_DIR/soap_srv/data /opt/soap_srv/data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv data
        exit 1
    fi

    ln -s $VAR_DIR/soap_srv/log /opt/soap_srv/log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln soap_srv log
        exit 1
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/soap_srv-$SOAP_VER-$DISTRO-x86_64 /opt/soap_srv $VAR_DIR/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to chown for opt/soap_srv var/soap_srv
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
