#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    pacman -Syu --noconfirm \
        base-devel  \
        openssl \
        ncurses \
        jdk7-openjdk \
        fop \
        libxslt \
        git \
        screen \
        net-snmp \
        htop \
        sysstat \
        iotop \
        wget \
        curl \
        sudo \
        tar

    if [[ $? -ne 0 ]]; then
        echo Failed to install deps
        exit 1
    fi

    # setup kerl (https://github.com/yrashk/kerl)
    cat > ~/.kerlrc <<EOF
export $ERLANG_ENV
KERL_CONFIGURE_OPTIONS="--without-wx --without-javac --without-odbc"
KERL_DEFAULT_INSTALL_DIR=/opt
KERL_INSTALL_MANPAGES=1
KERL_INSTALL_HTMLDOCS=1
EOF
    pushd /opt/bin
    curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
    chmod a+x kerl

    pushd /etc/bash_completion.d
    curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/bash_completion/kerl
    popd
    popd

    wget --continue https://aur.archlinux.org/packages/to/tokyocabinet/tokyocabinet.tar.gz
    tar -xzf tokyocabinet.tar.gz
    pushd tokyocabinet
    makepkg -s --asroot
    pacman -U --noconfirm tokyocabinet-1.4.48-1-$(uname -m).pkg.tar.xz
    ret=$?
    popd
    rm -rf tokyocabinet*

    if [[ $ret -ne 0 ]]; then
        echo Failed to install tokyocabinet
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
