#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

source $SCRIPT_DIR/phase-check-args

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    rm -rf ${TMP_DIR?}/kelly

    git clone https://github.com/PowerMeMobile/kelly.git ${TMP_DIR?}/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to clone kelly
        exit 1
    fi

    pushd ${TMP_DIR?}/kelly

    git checkout $KELLY_VER
    if [[ $? -ne 0 ]]; then
        echo Failed to checkout kelly $KELLY_VER
        popd
        exit 1
    fi

    make
    if [[ $? -ne 0 ]]; then
        echo Failed to build kelly
        popd
        exit 1
    fi

    DIR_NAME=kelly-${KELLY_VER}
    TAR_NAME=${DIR_NAME}-${DISTRO}.$(uname -m).tar.gz

    mv rel/kelly ${DIR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to rename kelly release
        popd
        exit 1
    fi

    tar -czf ${TAR_NAME} ${DIR_NAME}/
    if [[ $? -ne 0 ]]; then
        echo Failed to pack kelly
        popd
        exit 1
    fi

    popd

    mv ${TMP_DIR?}/kelly/${TAR_NAME} $SCRIPT_DIR/../distr/
    if [[ $? -ne 0 ]]; then
        echo Failed to move kelly to distr
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
