#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_JUST == true ]]; then
        $SCRIPT_DIR/phase-build-just $* || exit $?
    fi

    PROJ_NAME=just-mini_${JUST_VER}_${DISTRO}_$(uname -m)

    tar -C /opt -xzf $SCRIPT_DIR/../distr/${PROJ_NAME}.tar.gz
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack just
        exit 1
    fi

    mkdir -p $DATA_DIR/just/data $LOG_DIR/just
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir just
        exit 1
    fi

    pushd /opt/${PROJ_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to change dir to /opt/${PROJ_NAME}
        exit 1
    fi

    cp -r -u data/* $DATA_DIR/just/data
    if [[ $? -ne 0 ]]; then
        echo Failed to copy just data
        exit 1
    fi

    cp -r -u log/* $LOG_DIR/just
    if [[ $? -ne 0 ]]; then
        echo Failed to copy just log
        exit 1
    fi

    rm -rf data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm just data
        exit 1
    fi

    rm -rf log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm just log
        exit 1
    fi

    ln -s $DATA_DIR/just/data data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln just data
        exit 1
    fi

    ln -s $LOG_DIR/just log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln just log
        exit 1
    fi

    popd

    # remove old link
    previous=`readlink /opt/just`
    if [[ "$previous" != "" ]]; then
        rm /opt/just
    fi

    # setup link
    ln -s /opt/${PROJ_NAME} /opt/just
    if [[ $? -ne 0 ]]; then
        echo Failed to ln just
        exit 1
    fi

    # change app configuration warning
    if [[ "$previous" != "" ]]; then
        echo diff $previous/releases/1/sys.config /opt/just/releases/1/sys.config
        diff $previous/releases/1/sys.config /opt/just/releases/1/sys.config
        if [[ $? -ne 0 ]]; then
            cat << EOF
WARNING!
Don't forget to change application configuration.
EOF
        fi
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/${PROJ_NAME} /opt/just $DATA_DIR/just $LOG_DIR/just
    if [[ $? -ne 0 ]]; then
        echo Failed to chown just
        exit 1
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/${PROJ_NAME} /opt/just $DATA_DIR/just $LOG_DIR/just
    if [[ $? -ne 0 ]]; then
        echo Failed to chown just
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
