#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_KELLY == true ]]; then
        $SCRIPT_DIR/phase-build-kelly $* || exit $?
    fi

    DIR_NAME=kelly-${KELLY_VER}
    TAR_NAME=kelly_${KELLY_VER}_${DISTRO}_$(uname -m).tar.gz

    tar -C /opt -xzf $SCRIPT_DIR/../distr/${TAR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack kelly
        exit 1
    fi

    mkdir -p $DATA_DIR/kelly/data $LOG_DIR/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir kelly
        exit 1
    fi

    pushd /opt/${DIR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to change dir to /opt/${DIR_NAME}
        exit 1
    fi

    #cp -r -u data/* $DATA_DIR/kelly/data
    #if [[ $? -ne 0 ]]; then
    #    echo Failed to copy kelly data
    #    exit 1
    #fi

    #cp -r -u log/* $LOG_DIR/kelly
    #if [[ $? -ne 0 ]]; then
    #    echo Failed to copy kelly log
    #    exit 1
    #fi

    rm -rf data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm kelly data
        exit 1
    fi

    rm -rf log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm kelly log
        exit 1
    fi

    ln -s $DATA_DIR/kelly/data data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln kelly data
        exit 1
    fi

    ln -s $LOG_DIR/kelly log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln kelly log
        exit 1
    fi

    popd

    # remove old link
    previous=`readlink /opt/kelly`
    if [[ "$previous" != "" ]]; then
        rm /opt/kelly
    fi

    # setup link
    ln -s /opt/${DIR_NAME} /opt/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to ln kelly
        exit 1
    fi

    # change app configuration warning
    if [[ "$previous" != "" ]]; then
        echo diff $previous/releases/1/sys.config /opt/kelly/releases/1/sys.config
        diff $previous/releases/1/sys.config /opt/kelly/releases/1/sys.config
        if [[ $? -ne 0 ]]; then
            cat << EOF
WARNING!
Don't forget to change application configuration.
EOF
        fi
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/${DIR_NAME} /opt/kelly $DATA_DIR/kelly $LOG_DIR/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to chown kelly
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
