#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_KELLY == true ]]; then
        rm -rf $TMP_DIR/kelly

        git clone https://github.com/PowerMeMobile/kelly.git $TMP_DIR/kelly
        if [[ $? -ne 0 ]]; then
            echo Failed to clone kelly
            exit 1
        fi

        pushd $TMP_DIR/kelly

        git checkout $KELLY_VER
        if [[ $? -ne 0 ]]; then
            echo Failed to checkout kelly $KELLY_VER
            popd
            exit 1
        fi

        make
        if [[ $? -ne 0 ]]; then
            echo Failed to build kelly
            popd
            exit 1
        fi

        mv rel/kelly kelly-$KELLY_VER-$DISTRO-x86_64
        if [[ $? -ne 0 ]]; then
            echo Failed to rename kelly release
            popd
            exit 1
        fi

        tar -czf kelly-$KELLY_VER-$DISTRO-x86_64.tar.gz kelly-$KELLY_VER-$DISTRO-x86_64/
        if [[ $? -ne 0 ]]; then
            echo Failed to pack kelly
            popd
            exit 1
        fi

        popd

        mv $TMP_DIR/kelly/kelly-$KELLY_VER-$DISTRO-x86_64.tar.gz $SCRIPT_DIR/../distr/
        if [[ $? -ne 0 ]]; then
            echo Failed to move kelly to distr
            popd
            exit 1
        fi

    fi

    tar -C /opt -xzf $SCRIPT_DIR/../distr/kelly-$KELLY_VER-$DISTRO-x86_64.tar.gz
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack kelly
        exit 1
    fi

    # TODO: on upgrade the link may already exist
    ln -s /opt/kelly-$KELLY_VER-$DISTRO-x86_64 /opt/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to ln kelly
        exit 1
    fi

    # create Kelly dirs
    mkdir -p $DATA_DIR/kelly $LOG_DIR/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir kelly
        exit 1
    fi

    cp -r /opt/kelly/data $DATA_DIR/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to copy kelly data
        exit 1
    fi

    cp -r /opt/kelly/log/* $LOG_DIR/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to copy kelly log
        exit 1
    fi

    rm -rf /opt/kelly/data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm kelly data
        exit 1
    fi

    rm -rf /opt/kelly/log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm kelly log
        exit 1
    fi

    ln -s $DATA_DIR/kelly/data /opt/kelly/data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln kelly data
        exit 1
    fi

    ln -s $LOG_DIR/kelly /opt/kelly/log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln kelly log
        exit 1
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/kelly-$KELLY_VER-$DISTRO-x86_64 /opt/kelly $DATA_DIR/kelly $LOG_DIR/kelly
    if [[ $? -ne 0 ]]; then
        echo Failed to chown kelly
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
