#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    rm -rf $TMP_DIR/just_mini

    git clone https://github.com/PowerMeMobile/just_mini_rel.git $TMP_DIR/just_mini
    if [[ $? -ne 0 ]]; then
        echo Failed to clone just
        exit 1
    fi

    pushd $TMP_DIR/just_mini

    git checkout $JUST_VER
    if [[ $? -ne 0 ]]; then
        echo Failed to checkout just $JUST_VER
        popd
        exit 1
    fi

    make
    if [[ $? -ne 0 ]]; then
        echo Failed to build just
        popd
        exit 1
    fi

    mv just_mini just_mini-$JUST_VER-$DISTRO-x86_64
    if [[ $? -ne 0 ]]; then
        echo Failed to rename just release
        popd
        exit 1
    fi

    tar -czf just_mini-$JUST_VER-$DISTRO-x86_64.tar.gz just_mini-$JUST_VER-$DISTRO-x86_64/
    if [[ $? -ne 0 ]]; then
        echo Failed to pack just
        popd
        exit 1
    fi

    popd

    mv $TMP_DIR/just_mini/just_mini-$JUST_VER-$DISTRO-x86_64.tar.gz $SCRIPT_DIR/../distr/
    if [[ $? -ne 0 ]]; then
        echo Failed to move just to distr
        popd
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
