#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

source $SCRIPT_DIR/phase-check-args

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    rm -rf ${TMP_DIR?}/oneapi_srv

    git clone https://github.com/PowerMeMobile/oneapi_srv.git ${TMP_DIR?}/oneapi_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to clone oneapi_srv
        exit 1
    fi

    pushd ${TMP_DIR?}/oneapi_srv

    git checkout $ONEAPI_SRV_VER
    if [[ $? -ne 0 ]]; then
        echo Failed to checkout oneapi_srv $ONEAPI_VER
        popd
        exit 1
    fi

    make
    if [[ $? -ne 0 ]]; then
        echo Failed to build oneapi_srv
        popd
        exit 1
    fi

    DIR_NAME=oneapi_srv-${ONEAPI_VER}
    TAR_NAME=${DIR_NAME}-${DISTRO}.$(uname -m).tar.gz

    mv rel/oneapi_srv ${DIR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to rename oneapi_srv release
        popd
        exit 1
    fi

    tar -czf ${TAR_NAME} ${DIR_NAME}/
    if [[ $? -ne 0 ]]; then
        echo Failed to pack oneapi_srv
        popd
        exit 1
    fi

    popd

    mv ${TMP_DIR?}/oneapi_srv/${TAR_NAME} $SCRIPT_DIR/../distr/
    if [[ $? -ne 0 ]]; then
        echo Failed to move oneapi_srv to distr
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
