#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    kerl build $ERLANG_VER ${ERLANG_VER,,}
    if [[ $? -ne 0 ]]; then
        echo Failed to build erlang
        exit 1
    fi

    kerl install ${ERLANG_VER,,}
    if [[ $? -ne 0 ]]; then
        echo Failed to install erlang
        exit 1
    fi

    echo -e "\nsource /opt/${ERLANG_VER,,}/activate" >> /etc/profile
    if [[ $? -ne 0 ]]; then
        echo Failed to add erlang activate to profile
        exit 1
    fi

    source /opt/${ERLANG_VER,,}/activate

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
