#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

source $SCRIPT_DIR/phase-check-args

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    rm -rf ${TMP_DIR?}/soap_srv

    git clone https://github.com/PowerMeMobile/soap_srv.git ${TMP_DIR?}/soap_srv
    if [[ $? -ne 0 ]]; then
        echo Failed to clone soap_srv
        exit 1
    fi

    pushd ${TMP_DIR?}/soap_srv

    git checkout $SOAP_SRV_VER
    if [[ $? -ne 0 ]]; then
        echo Failed to checkout soap_srv $SOAP_VER
        popd
        exit 1
    fi

    make
    if [[ $? -ne 0 ]]; then
        echo Failed to build soap_srv
        popd
        exit 1
    fi

    PROJ_NAME=soap-srv_${SOAP_VER}_${DISTRO}_$(uname -m)

    mv rel/soap_srv ${PROJ_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to rename soap_srv release
        popd
        exit 1
    fi

    tar -czf ${PROJ_NAME}.tar.gz ${PROJ_NAME}/
    if [[ $? -ne 0 ]]; then
        echo Failed to pack soap_srv
        popd
        exit 1
    fi

    popd

    mv ${TMP_DIR?}/soap_srv/${PROJ_NAME}.tar.gz $SCRIPT_DIR/../distr/
    if [[ $? -ne 0 ]]; then
        echo Failed to move soap_srv to distr
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
