#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    if [[ $BUILD_FUNNEL == true ]]; then
        source $SCRIPT_DIR/phase-build-funnel
    fi

    tar -C /opt -xzf $SCRIPT_DIR/../distr/funnel_mini-$FUNNEL_VER-$DISTRO-x86_64.tar.gz
    if [[ $? -ne 0 ]]; then
        echo Failed to unpack funnel
        exit 1
    fi

    # TODO: on upgrade the link may already exist
    ln -s /opt/funnel_mini-$FUNNEL_VER-$DISTRO-x86_64 /opt/funnel
    if [[ $? -ne 0 ]]; then
        echo Failed to ln funnel
        exit 1
    fi

    # create Funnel dirs
    mkdir -p $DATA_DIR/funnel $LOG_DIR/funnel
    if [[ $? -ne 0 ]]; then
        echo Failed to mkdir funnel
        exit 1
    fi

    cp -r /opt/funnel/data $DATA_DIR/funnel
    if [[ $? -ne 0 ]]; then
        echo Failed to copy funnel data
        exit 1
    fi

    cp -r /opt/funnel/log/* $LOG_DIR/funnel
    if [[ $? -ne 0 ]]; then
        echo Failed to copy funnel log
        exit 1
    fi

    rm -rf /opt/funnel/data
    if [[ $? -ne 0 ]]; then
        echo Failed to rm funnel data
        exit 1
    fi

    rm -rf /opt/funnel/log
    if [[ $? -ne 0 ]]; then
        echo Failed to rm funnel log
        exit 1
    fi

    ln -s $DATA_DIR/funnel/data /opt/funnel/data
    if [[ $? -ne 0 ]]; then
        echo Failed to ln funnel data
        exit 1
    fi

    ln -s $LOG_DIR/funnel /opt/funnel/log
    if [[ $? -ne 0 ]]; then
        echo Failed to ln funnel log
        exit 1
    fi

    # setup file system permissions
    chown $ALLEY_USER:$ALLEY_USER -R /opt/funnel_mini-$FUNNEL_VER-$DISTRO-x86_64 /opt/funnel $DATA_DIR/funnel $LOG_DIR/funnel
    if [[ $? -ne 0 ]]; then
        echo Failed to chown funnel
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
