#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

source $SCRIPT_DIR/phase-check-args

grep -q $SCRIPT_NAME $SCRIPT_DIR/../log/setup.log
if [[ $? -eq 1 ]]; then
    source $SCRIPT_DIR/../conf/setup.conf

    rm -rf ${TMP_DIR?}/just_mini

    git clone https://github.com/PowerMeMobile/just_mini.git ${TMP_DIR?}/just_mini
    if [[ $? -ne 0 ]]; then
        echo Failed to clone just
        exit 1
    fi

    pushd ${TMP_DIR?}/just_mini

    git checkout $JUST_VER
    if [[ $? -ne 0 ]]; then
        echo Failed to checkout just $JUST_VER
        popd
        exit 1
    fi

    make
    if [[ $? -ne 0 ]]; then
        echo Failed to build just
        popd
        exit 1
    fi

    DIR_NAME=just-mini-${JUST_VER}
    TAR_NAME=just-mini_${JUST_VER}_${DISTRO}_$(uname -m).tar.gz

    mv rel/just_mini ${DIR_NAME}
    if [[ $? -ne 0 ]]; then
        echo Failed to rename just release
        popd
        exit 1
    fi

    tar -czf ${TAR_NAME} ${DIR_NAME}/
    if [[ $? -ne 0 ]]; then
        echo Failed to pack just
        popd
        exit 1
    fi

    popd

    mv ${TMP_DIR?}/just_mini/${TAR_NAME} $SCRIPT_DIR/../distr/
    if [[ $? -ne 0 ]]; then
        echo Failed to move just to distr
        exit 1
    fi

    echo $SCRIPT_NAME >> $SCRIPT_DIR/../log/setup.log
    echo "DONE"
else
    echo "SKIPPED"
fi
