#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

if [[ "$(id -un)" != "root" ]]; then
    echo "Must be root"
    exit 1
fi

touch $SCRIPT_DIR/../log/setup.log

source $SCRIPT_DIR/phase-check-args

source $SCRIPT_DIR/phase-make-dirs
source $SCRIPT_DIR/phase-install-deps-${DISTRO_FAMILY}
source $SCRIPT_DIR/phase-setup-snmp
source $SCRIPT_DIR/phase-add-users-${DISTRO_FAMILY}
source $SCRIPT_DIR/phase-setup-limits
source $SCRIPT_DIR/phase-setup-erlang
source $SCRIPT_DIR/phase-setup-mongodb
source $SCRIPT_DIR/phase-setup-rabbitmq
source $SCRIPT_DIR/phase-setup-rabbitmq_management
source $SCRIPT_DIR/phase-setup-smppsim
source $SCRIPT_DIR/phase-setup-smppload
source $SCRIPT_DIR/phase-env-cleanup
