#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

if [[ "$(id -un)" != "root" ]]; then
    echo "Must be root"
    exit 1
fi

touch $SCRIPT_DIR/../log/setup.log

source $SCRIPT_DIR/phase-check-args

source $SCRIPT_DIR/phase-setup-funnel
source $SCRIPT_DIR/phase-setup-soap
source $SCRIPT_DIR/phase-setup-oneapi
#source $SCRIPT_DIR/phase-setup-mm
source $SCRIPT_DIR/phase-setup-kelly
source $SCRIPT_DIR/phase-setup-just
source $SCRIPT_DIR/phase-alley-cleanup
