#!/bin/bash

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})

echo "#"
echo "# $SCRIPT_NAME"
echo "#"

if [[ "$(id -un)" != "root" ]]; then
    echo "Must be root"
    exit 1
fi

function usage() {
    echo "Usage: $SCRIPT_NAME <centos6 | fedora20 | rhel6 | debian7 | ubuntu10.04| ubuntu12.04 | arch>"
}

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

export DISTRO="$1"

case ${DISTRO} in
    centos*|fedora*|rhel*)
        export DISTRO_FAMILY="redhat"
        ;;
    debian*|ubuntu*)
        export DISTRO_FAMILY="debian"
        ;;
    arch)
        export DISTRO_FAMILY="arch"
        ;;
    *)
        usage
        exit 1
        ;;
esac

touch $SCRIPT_DIR/../log/setup.log

source $SCRIPT_DIR/phase-setup-funnel
source $SCRIPT_DIR/phase-setup-just
source $SCRIPT_DIR/phase-setup-kelly
source $SCRIPT_DIR/phase-setup-soap
#source $SCRIPT_DIR/phase-setup-oneapi
source $SCRIPT_DIR/phase-setup-snmp
source $SCRIPT_DIR/phase-alley-cleanup
